name: PR CHECK

on:
  pull_request:
    branches:
      - dev
      - main
      - master

jobs:
  ci:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build
